env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "DjabyNHZQy/AwrBl5cJ51OHhrMeCDsgJRyoaPcmug9WDcNsKfuQ8hRs6k7i2+fIeZXZBNJ102F8FJfv+dshzzJMFDFUxeDa8t2w2T2poE/r5qdCCcQFTxtmMqmX0xZwYkD8HtkWy0KMpK4OL4z/6QXVl6uzfB3efSIRgJMCOkXop0iK5qdvEFq5alphQdHpT7SdDoknSbyQmOmkQynEoLSlyChpckKJ8Oc2/Mrb3AAIJmUYtcSH3E2icTSZDMq9ljk4P8aVSD4gdBXkOfM7nTdphT9GsmuG6GffqJwyHEbMiilkWBpSsAWxW14w/jY41gSJ4YHHsCiGLzSA/zCuJv9pjv34/HkEcze/qnUlhc43RkKsjFhUMGk+gKLhCSmPgoyFxVLCeetMSe0Ymlq9EpUCPVvnN9iM0ws9E2jU6+Xy//jD9dVCsjnUHJ1eHvSEIF9EvdkXJBs0b2f1b12lEuUiOViP5Jl4ews86jWFeom72R1fjkNOQ63srSbKxWOMghIgDh50vIdTnACLFeEfaBaFMAgIQl4Nwr/Du0XrMUu4GB/ssKkVC+YgbXWxr/p9R8f7pdhdDsFdpzfmSZOQcPqXG+FJUS183tU/3dqhBw749U4azXdbAUTD6eXdrSJFrndaP9k9n9tFMavkd4QPhPXrbMwUWLJvVjBraefjbq3U="

language: c

os:
    - linux

dist: trusty
sudo: required

branches:
    only:
        - coverity-scan

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:441 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - wget -c http://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - tar xf gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - export PATH=$PATH:$PWD/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/bin/
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export NUMCPUS=`nproc`
    - export XEN_TARGET_ARCH=arm64

addons:
    coverity_scan:
        project:
            name: "xen-troops/optee_os"
            description: "Build submitted via Travis CI"
        notification_email: joculator@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler aarch64-linux-gnu-gcc --template"
        build_command: "make -j$NUMCPUS PLATFORM=rpi3 CFG_ARM64_core=y"
        branch_pattern: coverity-scan

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j$NUMCPUS PLATFORM=rpi3 CFG_ARM64_core=y; fi

